---
title: "NA-SITB meta"
author: "Kevin Kuehn"
date: "9/16/2020"
output: 
  html_document:
    toc: true
    toc_float: true
    toc_collapsed: true
    toc_depth: 3
  theme: united
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=FALSE, warning=FALSE, error=TRUE)


library(foreign)
library(psycho)
library(psych)
library(misty)
library(ANOVAreplication)
library(corrplot)
library(DataCombine)
library(tidyr)
library(naniar)
library(plyr)
library(dplyr)
library(meta)
library(metafor)
```

```{r, echo=FALSE}
#' Perform Egger's test of the intercept
#'
#' This function performs Egger's test of the intercept for funnel plot asymmetry using an object
#' of class \code{meta}.
#'
#' @usage eggers.test(x)
#'
#' @param x An object of class \code{meta}, generated by the \code{metabin}, \code{metagen},
#' \code{metacont}, \code{metacor}, \code{metainc}, or \code{metaprop} function.
#'
#' @details Performs Egger's test (Egger et al., 1997) for funnel plot asymmetry.
#' The \code{\link[meta]{metabias}} function is called internally. Egger's test may lack
#' the statistical power to detect bias when the number of studies is small. Sterne et al.
#' (2011) recommend to perform funnel plot asymmetry tests only when \eqn{k \geq 10}. A warning
#' is therefore printed when the number of studies in the \code{meta} object is \eqn{k < 10}.
#'
#' @references
#'
#' Harrer, M., Cuijpers, P., Furukawa, T.A, & Ebert, D. D. (2019).
#' \emph{Doing Meta-Analysis in R: A Hands-on Guide}. DOI: 10.5281/zenodo.2551803. \href{https://bookdown.org/MathiasHarrer/Doing_Meta_Analysis_in_R/smallstudyeffects.html}{Chapter 9.1}
#'
#' Egger M, Smith GD, Schneider M & Minder C (1997), Bias in meta-analysis detected by a simple,
#' graphical test. \emph{BMJ}, 315, 629–634.
#'
#' Sterne, JAC et al. (2011), Recommendations for Examining and Interpreting Funnel Plot
#' Asymmetry in Meta-Analyses of Randomised Controlled Trials. \emph{BMJ}
#' 343, 1, doi: 10.1136/bmj.d4002 .
#'
#' @author Mathias Harrer & David Daniel Ebert
#'
#' @importFrom meta metabias
#' @importFrom graphics abline axis lines mtext par plot points rect segments text
#' @importFrom stats as.formula hat influence ks.test optimize pbinom pchisq pf pnorm pt punif qchisq qf qnorm qt reformulate reorder setNames uniroot
#'
#' @return Returns a list containing the following elements:
#' \itemize{
#' \item \code{intercept}: The intercept (bias).
#' \item \code{llci}: The lower bound of the 95\% intercept confidence interval.
#' \item \code{ulci}: The upper bound of the 95\% intercept confidence interval.
#' \item \code{t}: The t-statistic for the intercept test.
#' \item \code{p}: The \eqn{p}-value for Egger's test.
#' \item \code{meta.obj}: The meta-analysis object of class \code{meta} originally provided
#' to the function.
#' }
#'
#' @export eggers.test
#'
#' @seealso \code{\link[meta]{metabias}}
#'
#' @examples
#' # Create meta-analysis results using the 'metagen' function
#' suppressPackageStartupMessages(library(meta))
#' data(ThirdWave)
#' m = metagen(TE, seTE, studlab = paste(Author),
#'     data = ThirdWave, comb.random = FALSE, hakn=TRUE)
#'
#' # Plug result into 'eggers.test' function
#' res.et <- eggers.test(m)
#'
#' # Inspect the results
#' summary(res.et)
#'
#' # Generate a funnel plot. This calls the 'funnel' function
#' # in 'meta' internally; additional parameters of this function can also
#' # be provided (see '?meta::funnel').
#' plot(res.et, bg = "lightblue")


eggers.test = function(x) {

    # Validate
    x = x

    if (x$k < 10) {

        warning(paste("Your meta-analysis contains k =",
                      x$k, "studies. Egger's test may lack the statistical power to detect bias when the number of studies is small (i.e., k<10)."))

    }

    if (class(x)[1] %in% c("meta", "metabin", "metagen", "metacont", "metacor", "metainc", "metaprop")) {

        # Conduct metabias
        eggers = meta::metabias(x, k.min = 3, method = "linreg")

        # Get Intercept
        intercept = as.numeric(eggers$estimate[1])

        # Get SE
        se = as.numeric(eggers$estimate[2])

        # Calculate 95CI
        llci = intercept - qnorm(0.975) * se
        ulci = intercept + qnorm(0.975) * se

        # Get t
        t = as.numeric(eggers$statistic)

        # Get df
        df = as.numeric(eggers$parameters)

        # Get p
        p = as.numeric(eggers$p.value)

        # Make df
        returnlist = list(intercept = intercept,
                          llci = llci,
                          ulci = ulci,
                          t = t,
                          p = p,
                          meta.obj = x)

    } else {

        stop("x must be of type 'metabin', 'metagen', 'metacont', 'metainc' or 'metaprop'")

    }

    class(returnlist) = "eggers.test"

    return(returnlist)

}
```

```{r, echo=FALSE}
#' Find Statistical Outliers in a Meta-Analysis
#'
#' Searches for statistical outliers in meta-analysis results generated by \code{\link[meta]{meta}} functions or the
#' \code{\link[metafor]{rma.uni}} in the \code{metafor} package.
#'
#' @usage find.outliers(x, ...)
#'
#' @param x Either (1) an object of class \code{meta}, generated by the \code{metabin}, \code{metagen},
#' \code{metacont}, \code{metacor}, \code{metainc}, \code{metarate} or \code{metaprop} function; or (2)
#' and object of class \code{rma.uni} created with the \code{\link[metafor]{rma.uni}} function in \code{metafor}.
#' @param ... Additional parameters for the \code{\link[metafor]{rma.uni}} or \code{\link[meta]{update.meta}} function.
#'
#' @details
#' This function searches for outlying studies in a meta-analysis results object. Studies are defined as outliers when
#' their 95\% confidence interval lies ouside the 95\% confidence interval of the pooled effect.
#'
#' When outliers are found, the function automatically recalculates the meta-analysis results, using the same settings as
#' in the object provided in \code{x}, but excluding the detected outliers.
#'
#' A forest plot of the meta-analysis with outliers removed can be generated directly by plugging the output of the function into
#' the \code{forest} function.
#'
#' @references Harrer, M., Cuijpers, P., Furukawa, T.A, & Ebert, D. D. (2019).
#' \emph{Doing Meta-Analysis in R: A Hands-on Guide}. DOI: 10.5281/zenodo.2551803. \href{https://bookdown.org/MathiasHarrer/Doing_Meta_Analysis_in_R/detecting-outliers-influential-cases.html}{Chapter 6.2}
#'
#' @author Mathias Harrer & David Daniel Ebert
#'
#' @return
#' Returns the identified outliers and the meta-analysis results when the outliers are removed.
#'
#' If the provided meta-analysis object is of class \code{meta}, the following objects are returned if the
#' results of the function are saved to another object:
#' \itemize{
#' \item \code{out.study.fixed}: A numeric vector containing the names of the outlying studies when
#' assuming a fixed-effect model.
#' \item \code{out.study.random}: A numeric vector containing the names of the outlying studies when
#' assuming a random-effects model. The \eqn{\tau^{2}} estimator \code{method.tau} is inherited from \code{x}.
#' \item \code{m.fixed}: An object of class \code{meta} containing the results of the meta-analysis with outliers
#' removed (assuming a fixed-effect model).
#' \item \code{m.random}: An object of class \code{meta} containing the results of the meta-analysis with outliers
#' removed (assuming a random-effects model, and using the same \code{method.tau} as in the original analysis).
#'}
#'
#' If the provided meta-analysis object is of class \code{rma.uni}, the following objects are returned if the
#' results of the function are saved to another object:
#' \itemize{
#' \item \code{out.study}: A numeric vector containing the names of the outlying studies.
#' \item \code{m}: An object of class \code{rma.uni} containing the results of the meta-analysis with outliers
#' removed (using the same settings as in the meta-analysis object provided).
#'}
#' @importFrom metafor rma.uni
#' @importFrom meta update.meta
#'
#' @export find.outliers
#'
#' @aliases spot.outliers.random spot.outliers.fixed spot.outliers
#'
#' @seealso \code{\link[metafor]{influence.rma.uni}}, \code{\link[meta]{metainf}}, \code{\link[meta]{baujat}}
#'
#' @examples
#' suppressPackageStartupMessages(library(meta))
#' suppressPackageStartupMessages(library(metafor))
#' suppressPackageStartupMessages(library(dmetar))
#'
#' # Pool with meta
#' m1 <- metagen(TE, seTE, data = ThirdWave,
#'               studlab = ThirdWave$Author, comb.fixed = FALSE)
#'
#' # Pool with metafor
#' m2 <- rma(yi = TE, sei = seTE, data = ThirdWave,
#'           slab = ThirdWave$Author, method = "PM")
#'
#' # Find outliers
#' fo1 <- find.outliers(m1)
#' fo2 <- find.outliers(m2)
#'
#' # Show summary
#' summary(fo1)
#' summary(fo2)
#'
#' \dontrun{
#' # Make forest plot
#' # Pass additional arguments from meta & metafor's forest function
#' forest(fo1, prediction = TRUE)
#' forest(fo2, cex = .8, col = "lightblue")
#' }


find.outliers = spot.outliers.random = spot.outliers.fixed = function(x, ...){


  if (class(x)[1] %in% c("rma.uni", "rma")){

    token = "metafor"

    # Generate lower/upper for all effects
    lower = as.numeric(x$yi - 1.96*sqrt(x$vi))
    upper = as.numeric(x$yi + 1.96*sqrt(x$vi))

    # Select outliers
    mask = upper < x$ci.lb | lower > x$ci.ub
    dat = data.frame("yi" = x$yi[!mask],
                     "vi" = x$vi[!mask],
                     "studlab" = as.character(x$slab[!mask]))
    out.study = x$slab[mask]

    # Update metafor model
    method.tau = x$method
    m = metafor::rma.uni(dat$yi, vi = dat$vi, method = method.tau, slab = dat$studlab, ...)

    if (length(out.study) < 1){


      tau.token = "metafor.null"
      cat(paste0("No outliers detected (", method.tau,")."))
      out.study = NULL

    } else {

      tau.token = "metafor"

    }

  }

  if (class(x)[1] %in% c("metagen", "metapropr",
                         "metacor", "metainc", "metacont",
                         "metaprop", "metabin", "metabin")){

    token = "meta"

    # Control for objects with NAs in study data
    if (sum(is.na(x$TE)) > 0 | sum(is.na(x$seTE)) > 0){

      stop("The provided 'meta' object cannot contain NA's in any of the study data.")

    }


    if (class(x)[1] == "metaprop"){

      lower = x$TE - 1.96*x$seTE
      upper = x$TE + 1.96*x$seTE

      # Generate mask with outliers (fixed/random)
      mask.fixed = upper < x$lower.fixed | lower > x$upper.fixed
      mask.random = upper < x$lower.random | lower > x$upper.random

    } else {

      # Generate mask with outliers (fixed/random)
      mask.fixed = x$upper < x$lower.fixed | x$lower > x$upper.fixed
      mask.random = x$upper < x$lower.random | x$lower > x$upper.random

    }

    # Update meta-analysis with outliers removed
    m.fixed = update.meta(x, exclude = mask.fixed, ...)
    m.random = update.meta(x, exclude = mask.random, ...)

    # Select names of outlying studies
    out.study.fixed = x$studlab[mask.fixed]
    out.study.random = x$studlab[mask.random]

    if (x$comb.fixed == TRUE & x$comb.random == FALSE){

      if (length(out.study.fixed) < 1){

        tau.token = "null.ftrf"
        out.study.fixed = NULL

      } else {

        tau.token = "ftrf"

      }

    }

    if (x$comb.fixed == FALSE & x$comb.random == TRUE){

      if (length(out.study.random) < 1){

        tau.token = "null.ffrt"
        out.study.random = NULL

      } else {

        tau.token = "ffrt"

      }

    }

    if (x$comb.fixed == TRUE & x$comb.random == TRUE){

      if (length(out.study.fixed) < 1 & length(out.study.random) < 1){

        out.study.fixed = NULL
        out.study.random = NULL
        tau.token = "null.ftrt"

      } else {

        if (length(out.study.fixed) < 1){out.study.fixed = NULL}
        if (length(out.study.random) < 1){out.study.random = NULL}

        tau.token = "ftrt"

      }

    }

  }

  if (!class(x)[1] %in% c("rma.uni", "rma", "metacont",
                          "metagen", "metapropr",
                          "metacor", "metainc",
                          "metaprop", "metabin", "metabin")){

    message("Input must be of class 'meta' or 'rma.uni'")

  }

  if (token == "metafor"){

    returnlist = list("out.study" = out.study,
                   "m" = m)

    if (tau.token == "metafor"){class(returnlist) = c("find.outliers", "mf", method.tau)}
    if (tau.token == "metafor.null"){class(returnlist) = c("find.outliers", "mf.null", method.tau)}

    # Return
    invisible(returnlist)

    returnlist

  } else {


    returnlist = list("out.study.fixed" = out.study.fixed,
                   "out.study.random" = out.study.random,
                   "m.fixed" = m.fixed,
                   "m.random" = m.random)

    # Set classes
    if (tau.token == "ftrf"){class(returnlist) = c("find.outliers", "ftrf")}
    if (tau.token == "ffrt"){class(returnlist) = c("find.outliers", "ffrt")}
    if (tau.token == "ftrt"){class(returnlist) = c("find.outliers", "ftrt")}
    if (tau.token == "null.ftrf"){class(returnlist) = c("find.outliers", "null.ftrf")}
    if (tau.token == "null.ffrt"){class(returnlist) = c("find.outliers", "null.ffrt")}
    if (tau.token == "null.ftrt"){class(returnlist) = c("find.outliers", "null.ftrt")}

    # Return
    invisible(returnlist)

    returnlist

  }

}
```

# Reading in data

```{r}
data<-read.csv('/Users/kevinkuehn/Documents/Writing/Kuehn et al. Psych Bull/NA-SITB_meta/Data/meta data.csv')
```

# NSSI Thoughts

## Antecedent Model 

```{r, warning=FALSE}
dat.nssi.thoughts<-data[which(data$Study=="Andrewes et al., 2017"|data$Study=="Bresin et al. 2013"|data$Study=="Hochard et al., 2015"|data$Study=="Kuehn et al., In Prep"|data$Study=="Selby et al., 2018"|data$Study=="Kiekens et al., 2020"), ]

m.nssi.thoughts.a <- metagen(NSSI.thoughts_A,
                  SP_NSSI.thoughts_A,
                  data = dat.nssi.thoughts,
                  studlab = paste(Study),
                  comb.fixed = FALSE,
                  comb.random = TRUE,
                  method.tau = "ML",
                  hakn = TRUE,
                  prediction = TRUE,
                  sm = "MD")

m.nssi.thoughts.a

forest(m.nssi.thoughts.a, layout="RevMan5", digits.sd=2)

eggers.test(x = m.nssi.thoughts.a)
```

## Consequence Model

```{r, warning=FALSE}
m.nssi.thoughts.c <- metagen(NSSI.thoughts_C,
                  SP_NSSI.thoughts_C,
                  data = dat.nssi.thoughts,
                  studlab = paste(Study),
                  comb.fixed = FALSE,
                  comb.random = TRUE,
                  method.tau = "ML",
                  hakn = TRUE,
                  prediction = TRUE,
                  sm = "MD")

m.nssi.thoughts.c

forest(m.nssi.thoughts.c, layout="RevMan5", digits.sd=2)

eggers.test(x = m.nssi.thoughts.c)
```

# NSSI Urges

## Antecedent Model

```{r, warning=FALSE}
dat.nssi.urges<-data[which(data$Study=="Bresin et al. 2013"|data$Study=="Victor et al., 2018"|data$Study=="Lear et al., 2019"), ]

m.nssi.urges.a <- metagen(NSSI.urges_A,
                  SP_NSSI.urges_A,
                  data = dat.nssi.urges,
                  studlab = paste(Study),
                  comb.fixed = FALSE,
                  comb.random = TRUE,
                  method.tau = "ML",
                  hakn = TRUE,
                  prediction = TRUE,
                  sm = "MD")

m.nssi.urges.a

forest(m.nssi.urges.a, layout="RevMan5", digits.sd=2)

eggers.test(x = m.nssi.urges.a)
```

## Consequence Model

```{r, warning=FALSE}
m.nssi.urges.c <- metagen(NSSI.urges_C,
                  SP_NSSI.urges_C,
                  data = dat.nssi.urges,
                  studlab = paste(Study),
                  comb.fixed = FALSE,
                  comb.random = TRUE,
                  method.tau = "ML",
                  hakn = TRUE,
                  prediction = TRUE,
                  sm = "MD")

m.nssi.urges.c

forest(m.nssi.urges.c, layout="RevMan5", digits.sd=2)

eggers.test(x = m.nssi.urges.c)
```

# NSSI Behaviors

## Antecedent Model

```{r}
dat.nssi.behavior<-data[which(data$Study=="Andrewes et al., 2017"|data$Study=="Armey et al., 2011"|data$Study=="Bresin et al. 2013"|data$Study=="Czyz et al. 2017"|data$Study=="Hochard et al., 2015"|data$Study=="Houben et al 2017"|data$Study=="Kiekens et al., 2020"|data$Study=="Kuehn et al., In Prep"|data$Study=="Lear et al., 2019"|data$Study=="Muehlenkamp et al., 2009"|data$Study=="Santangelo et al., 2017"|data$Study=="Selby et al., 2013"|data$Study=="Selby et al., 2018"|data$Study=="Vansteelandt et al. 2017"| data$Study=="Wolford-Clevenger et al., 2019"), ]

m.nssi.behavior.a <- metagen(NSSI.behaviors_A,
                  SP_NSSI.behaviors_A,
                  data = dat.nssi.behavior,
                  studlab = paste(Study),
                  comb.fixed = FALSE,
                  comb.random = TRUE,
                  method.tau = "ML",
                  hakn = TRUE,
                  prediction = TRUE,
                  sm = "MD")

m.nssi.behavior.a

jpeg('NSSI behavior.antecedent.jpeg',
     width=10, height=6, units="in", res=300)
forest(m.nssi.behavior.a, layout="RevMan5", digits.sd=2)
dev.off()

m.nssi.ant<-rma(yi= NSSI.behaviors_A, sei=SP_NSSI.behaviors_A, data=dat.nssi.behavior)
myFunnel <- function(x, ...) {
    funnel(x,
           level=c(90, 95, 99), 
           shade = c("white", "grey75", "grey60"), 
           refline=0,
           back = "gray90",
           ...)
}

jpeg('NSSI behavior ant funnel.jpeg',
     width=8, height=6, units="in", res=300)
myFunnel(m.nssi.ant, main = "NSSI Behavior Antecedent")
dev.off()

a<-funnel(m.nssi.behavior.a, main="NSSI Behavior Antecedent", xlab="Mean Effect Size",
contour = c(.95,.975,.99),
col.contour=c("white", "grey75", "grey60"))
legend(1.1,0,c("p < 0.05", "p<0.025", "< 0.01"),bty = "n",
fill=c("white", "grey75", "grey60"))

jpeg('NSSI behavior ant funnel.gray.jpeg',
     width=8, height=6, units="in", res=300)
a
dev.off()

eggers.test(x = m.nssi.behavior.a)

ant.nssi<-find.outliers(m.nssi.behavior.a)

jpeg(file='NSSI behavior.ant.out.jpeg',
     width=10, height=6, units="in", res=300)
forest(ant.nssi$m.random, layout="RevMan5", digits.sd=2)
dev.off()

ant.nssi.comp<-metareg(ant.nssi$m.random, Compliance.rate)

bubble(ant.nssi.comp,
       xlab = "Compliance Rate",
       col.line = "blue",
       studlab = TRUE)

ant.nssi.freq<-metareg(ant.nssi$m.random, Frequency.of.NSSI.behaviors)

bubble(ant.nssi.freq,
       xlab = "Frequency of NSSI Behavior",
       col.line = "blue",
       studlab = TRUE)

ant.nssi.prompt<-metareg(ant.nssi$m.random, X..of.prompts.per.day)

bubble(ant.nssi.prompt,
       xlab = "# of prompts per day", ylab="Effect size", main="Meta-regression of prompts per day by effect size", 
       col.line = "blue",
       studlab = TRUE)

ant.nssi.dur<-metareg(ant.nssi$m.random, Hours.between.prompts)

bubble(ant.nssi.dur,
       xlab = "X..of.prompts.per.day",
       col.line = "blue",
       studlab = TRUE)

BPD.subgroup<-update.meta(ant.nssi$m.random, 
                             byvar=BPD, 
                             comb.random = TRUE, 
                             comb.fixed = FALSE)
BPD.subgroup
```

## Consequence Model

```{r, warning=FALSE}
m.nssi.behavior.c <- metagen(NSSI.behaviors_C,
                  SP_NSSI.behaviors_C,
                  data = dat.nssi.behavior,
                  studlab = paste(Study),
                  comb.fixed = FALSE,
                  comb.random = TRUE,
                  method.tau = "ML",
                  hakn = TRUE,
                  prediction = TRUE,
                  sm = "MD")

m.nssi.behavior.c

jpeg(file='NSSI behavior.consequence.jpeg',
     width=10, height=6, units="in", res=300)
forest(m.nssi.behavior.c, layout="RevMan5", digits.sd=2)
dev.off()

m.nssi.con<-rma(yi= NSSI.behaviors_C, sei=SP_NSSI.behaviors_C, data=dat.nssi.behavior)
jpeg('NSSI behavior con funnel',
     width=8, height=6, units="in", res=900)
myFunnel(m.nssi.con, main = "NSSI Behavior Consequence")
dev.off()

eggers.test(x = m.nssi.behavior.c)

con.nssi.bhx<-find.outliers(m.nssi.behavior.c)

jpeg(file='NSSI behavior.consequence.out.jpeg',
     width=10, height=6, units="in", res=300)
forest(con.nssi.bhx$m.random, layout="RevMan5", digits.sd=2)
dev.off()

con.nssi.comp<-metareg(con.nssi.bhx$m.random, Compliance)

bubble(con.nssi.comp,
       xlab = "Compliance Rate",
       col.line = "blue",
       studlab = TRUE)

con.nssi.freq<-metareg(con.nssi.bhx$m.random, Frequency.of.NSSI.behaviors)

bubble(con.nssi.freq,
       xlab = "Frequency of NSSI Behavior",
       col.line = "blue",
       studlab = TRUE)

con.nssi.prompt<-metareg(con.nssi.bhx$m.random, X..of.prompts.per.day)

bubble(con.nssi.prompt,
       xlab = "X..of.prompts.per.day",
       col.line = "blue",
       studlab = TRUE)

con.nssi.dur<-metareg(con.nssi.bhx$m.random, Hours.between.prompts)


bubble(con.nssi.dur,
       xlab = "X..of.prompts.per.day",
       col.line = "blue",
       studlab = TRUE)

BPD.subgroup<-update.meta(con.nssi.bhx$m.random, 
                             byvar=BPD, 
                             comb.random = TRUE, 
                             comb.fixed = FALSE)
BPD.subgroup
```

# Suicidal Thoughts

## Antecedent Model

```{r, warning=FALSE}
dat.suicidal.thoughts<-data[which(data$Study=="Bresin et al. 2013"|data$Study=="Czyz et al. 2017"|data$Study=="Forkmann et al., 2018"|data$Study=="Husky et al., 2017"|data$Study=="Kaurin et al., Under Review"|data$Study=="Kiekens et al., 2020"|data$Study=="Kleiman et al., 2017"|data$Study=="Kleiman et al., 2018"|data$Study=="Kuehn et al., In Prep"|data$Study=="Peters et al., 2020"|data$Study=="Salim et al., 2019"|data$Study=="Wolford-Clevenger et al., 2019"), ]

m.suicidal.thoughts.a <- metagen(Suicidal.thoughts_A,
                  SP_Suicidal.thoughts_A,
                  data = dat.suicidal.thoughts,
                  studlab = paste(Study),
                  comb.fixed = FALSE,
                  comb.random = TRUE,
                  method.tau = "ML",
                  hakn = TRUE,
                  prediction = TRUE,
                  sm = "MD")

m.suicidal.thoughts.a

jpeg('Sui Thoughts.antecedent.jpeg',
     width=10, height=6, units="in", res=300)
forest(m.suicidal.thoughts.a, layout="RevMan5", digits.sd=2)
dev.off()

eggers.test(x = m.suicidal.thoughts.a)

ant.sui<-find.outliers(m.suicidal.thoughts.a)

ant.sui.compt<-metareg(ant.sui$m.random, Compliance.rate)

bubble(con.sui.compt,
       xlab = "Compliance Rate",
       col.line = "blue",
       studlab = TRUE)

ant.sui.freq<-metareg(ant.sui$m.random, Frequency.of.suicidal.thoughts)

bubble(ant.sui.freq,
       xlab = "Frequency of Suicidal Thoughts",
       col.line = "blue",
       studlab = TRUE)

ant.sui.prompt<-metareg(ant.sui$m.random, X..of.prompts.per.day)

ant.sui.dur<-metareg(ant.sui$m.random, Hours.between.prompts)

BPD.subgroup<-update.meta(ant.sui$m.random, 
                             byvar=BPD, 
                             comb.random = TRUE, 
                             comb.fixed = FALSE)
BPD.subgroup

dat.suicidal.thoughts$Published<-c("Yes", "No", "Yes", "No", "No", "Yes", "Yes", "Yes", "No", "Yes", "Yes")

published.subgroup<-update.meta(m.suicidal.thoughts.a, 
                             byvar=Published, 
                             comb.random = TRUE, 
                             comb.fixed = FALSE)
published.subgroup
```

## Consequence Model

```{r, warning=FALSE}
m.suicidal.thoughts.c <- metagen(Suicidal.thoughts_C,
                  SP_Suicidal.thoughts_C,
                  data = dat.suicidal.thoughts,
                  studlab = paste(Study),
                  comb.fixed = FALSE,
                  comb.random = TRUE,
                  method.tau = "ML",
                  hakn = TRUE,
                  prediction = TRUE,
                  sm = "MD")

m.suicidal.thoughts.c

jpeg('Sui Thoughts.consequence.jpeg',
     width=10, height=6, units="in", res=300)
forest(m.suicidal.thoughts.c, layout="RevMan5", digits.sd=2)
dev.off()

funnel(m.suicidal.thoughts.c, xlab="Mean Difference", 
       contour = c(.95,.975,.99),
       col.contour=c("white", "grey75", "grey60"))+
    legend(1.4, 0, c("p < 0.05", "p<0.025", "< 0.01"),bty = "n",
           fill=c("white", "grey75", "grey60"))

eggers.test(x = m.suicidal.thoughts.c)

con.sui.tghts<-metareg(m.suicidal.thoughts.c, Compliance.rate)

bubble(con.sui.tghts,
       xlab = "Compliance Rate",
       col.line = "blue",
       studlab = TRUE)

con.sui.tghts<-metareg(m.suicidal.thoughts.c, Frequency.of.suicidal.thoughts)

bubble(con.sui.tghts,
       xlab = "Frequency of Suicidal Thoughts",
       col.line = "blue",
       studlab = TRUE)
```

# Suicidal Urges

## Antecedent

```{r}
dat.suicidal.urges<-data[which(data$Study=="Bresin et al. 2013"|data$Study=="Victor et al., 2018"), ]

m.suicidal.urges.a <- metagen(Suicidal.urges_A,
                  SP_Suicidal.urges_A,
                  data = dat.suicidal.urges,
                  studlab = paste(Study),
                  comb.fixed = FALSE,
                  comb.random = TRUE,
                  method.tau = "ML",
                  hakn = TRUE,
                  prediction = TRUE,
                  sm = "MD")

m.suicidal.urges.a

forest(m.suicidal.urges.a, layout="RevMan5", digits.sd=2)

eggers.test(x = m.suicidal.urges.a)
```

## Consequence

```{r}
m.suicidal.urges.c <- metagen(Suicidal.urges_C,
                  SP_Suicidal.urges_C,
                  data = dat.suicidal.urges,
                  studlab = paste(Study),
                  comb.fixed = FALSE,
                  comb.random = TRUE,
                  method.tau = "ML",
                  hakn = TRUE,
                  prediction = TRUE,
                  sm = "MD")

m.suicidal.urges.c

forest(m.suicidal.urges.c, layout="RevMan5", digits.sd=2)

eggers.test(x = m.suicidal.urges.c)
```

```{r}
data<-read.csv('/Users/kevinkuehn/Documents/Writing/Kuehn et al. Psych Bull/Data/kleiman.5.csv')
```

```{r, warning=FALSE}
dat.suicidal.thoughts<-data[which(data$Study=="Bresin et al. 2013"|data$Study=="Czyz et al. 2017"|data$Study=="Forkmann et al., 2018"|data$Study=="Husky et al., 2017"|data$Study=="Kaurin et al., Under Review"|data$Study=="Kiekens et al., 2020"|data$Study=="Kleiman et al., 2017"|data$Study=="Kleiman et al., 2018"|data$Study=="Kuehn et al., In Prep"|data$Study=="Peters et al., 2020"|data$Study=="Salim et al., 2019"|data$Study=="Wolford-Clevenger et al., 2019"), ]

m.suicidal.thoughts.a <- metagen(Suicidal.thoughts_A,
                  SP_Suicidal.thoughts_A,
                  data = dat.suicidal.thoughts,
                  studlab = paste(Study),
                  comb.fixed = FALSE,
                  comb.random = TRUE,
                  method.tau = "ML",
                  hakn = TRUE,
                  prediction = TRUE,
                  sm = "MD")

m.suicidal.thoughts.a

ant.sui<-find.outliers(m.suicidal.thoughts.a)

jpeg('Sui Thoughts.antecedent.5.jpeg',
     width=10, height=6, units="in", res=300)
forest(ant.sui$m.random, layout="RevMan5", digits.sd=2)
dev.off()
```

```{r}
m.suicidal.thoughts.c <- metagen(Suicidal.thoughts_C,
                  SP_Suicidal.thoughts_C,
                  data = dat.suicidal.thoughts,
                  studlab = paste(Study),
                  comb.fixed = FALSE,
                  comb.random = TRUE,
                  method.tau = "ML",
                  hakn = TRUE,
                  prediction = TRUE,
                  sm = "MD")

m.suicidal.thoughts.c

con.sui<-find.outliers(m.suicidal.thoughts.c)

jpeg('Sui Thoughts.consequence.5.jpeg',
     width=10, height=6, units="in", res=300)
forest(m.suicidal.thoughts.c, layout="RevMan5", digits.sd=2)
dev.off()
```

```{r}
data<-read.csv('/Users/kevinkuehn/Documents/Writing/Kuehn et al. Psych Bull/Data/kleiman.1.5.csv')
```

```{r, warning=FALSE}
dat.suicidal.thoughts<-data[which(data$Study=="Bresin et al. 2013"|data$Study=="Czyz et al. 2017"|data$Study=="Forkmann et al., 2018"|data$Study=="Husky et al., 2017"|data$Study=="Kaurin et al., Under Review"|data$Study=="Kiekens et al., 2020"|data$Study=="Kleiman et al., 2017"|data$Study=="Kleiman et al., 2018"|data$Study=="Kuehn et al., In Prep"|data$Study=="Peters et al., 2020"|data$Study=="Salim et al., 2019"|data$Study=="Wolford-Clevenger et al., 2019"), ]

m.suicidal.thoughts.a <- metagen(Suicidal.thoughts_A,
                  SP_Suicidal.thoughts_A,
                  data = dat.suicidal.thoughts,
                  studlab = paste(Study),
                  comb.fixed = FALSE,
                  comb.random = TRUE,
                  method.tau = "ML",
                  hakn = TRUE,
                  prediction = TRUE,
                  sm = "MD")

m.suicidal.thoughts.a

ant.sui<-find.outliers(m.suicidal.thoughts.a)

jpeg('Sui Thoughts.antecedent.1.5.jpeg',
     width=10, height=6, units="in", res=300)
forest(ant.sui$m.random, layout="RevMan5", digits.sd=2)
dev.off()
```

```{r}
m.suicidal.thoughts.c <- metagen(Suicidal.thoughts_C,
                  SP_Suicidal.thoughts_C,
                  data = dat.suicidal.thoughts,
                  studlab = paste(Study),
                  comb.fixed = FALSE,
                  comb.random = TRUE,
                  method.tau = "ML",
                  hakn = TRUE,
                  prediction = TRUE,
                  sm = "MD")

m.suicidal.thoughts.c

con.sui<-find.outliers(m.suicidal.thoughts.c)

jpeg('Sui Thoughts.consequence.1.5.jpeg',
     width=10, height=6, units="in", res=300)
forest(m.suicidal.thoughts.c, layout="RevMan5", digits.sd=2)
dev.off()
```


```{r}
data<-read.csv('/Users/kevinkuehn/Documents/Writing/Kuehn et al. Psych Bull/Data/kleiman.2.csv')
```

```{r, warning=FALSE}
dat.suicidal.thoughts<-data[which(data$Study=="Bresin et al. 2013"|data$Study=="Czyz et al. 2017"|data$Study=="Forkmann et al., 2018"|data$Study=="Husky et al., 2017"|data$Study=="Kaurin et al., Under Review"|data$Study=="Kiekens et al., 2020"|data$Study=="Kleiman et al., 2017"|data$Study=="Kleiman et al., 2018"|data$Study=="Kuehn et al., In Prep"|data$Study=="Peters et al., 2020"|data$Study=="Salim et al., 2019"|data$Study=="Wolford-Clevenger et al., 2019"), ]

m.suicidal.thoughts.a <- metagen(Suicidal.thoughts_A,
                  SP_Suicidal.thoughts_A,
                  data = dat.suicidal.thoughts,
                  studlab = paste(Study),
                  comb.fixed = FALSE,
                  comb.random = TRUE,
                  method.tau = "ML",
                  hakn = TRUE,
                  prediction = TRUE,
                  sm = "MD")

m.suicidal.thoughts.a

ant.sui<-find.outliers(m.suicidal.thoughts.a)

jpeg('Sui Thoughts.antecedent.2.jpeg',
     width=10, height=6, units="in", res=300)
forest(ant.sui$m.random, layout="RevMan5", digits.sd=2)
dev.off()
```

```{r}
m.suicidal.thoughts.c <- metagen(Suicidal.thoughts_C,
                  SP_Suicidal.thoughts_C,
                  data = dat.suicidal.thoughts,
                  studlab = paste(Study),
                  comb.fixed = FALSE,
                  comb.random = TRUE,
                  method.tau = "ML",
                  hakn = TRUE,
                  prediction = TRUE,
                  sm = "MD")

m.suicidal.thoughts.c

con.sui<-find.outliers(m.suicidal.thoughts.c)

jpeg('Sui Thoughts.consequence.2.jpeg',
     width=10, height=6, units="in", res=300)
forest(m.suicidal.thoughts.c, layout="RevMan5", digits.sd=2)
dev.off()
```

```{r}
data<-read.csv('/Users/kevinkuehn/Documents/Writing/Kuehn et al. Psych Bull/Data/t+1.csv')
```

```{r}
dat.nssi.behavior<-data[which(data$Study=="Andrewes et al., 2017"|data$Study=="Armey et al., 2011"|data$Study=="Bresin et al. 2013"|data$Study=="Czyz et al. 2017"|data$Study=="Hochard et al., 2015"|data$Study=="Houben et al 2017"|data$Study=="Kiekens et al., 2020"|data$Study=="Kuehn et al., In Prep"|data$Study=="Lear et al., 2019"|data$Study=="Muehlenkamp et al., 2009"|data$Study=="Santangelo et al., 2017"|data$Study=="Selby et al., 2013"|data$Study=="Selby et al., 2018"|data$Study=="Vansteelandt et al. 2017"| data$Study=="Wolford-Clevenger et al., 2019"), ]

m.nssi.behavior.c <- metagen(NSSI.behaviors_C,
                  SP_NSSI.behaviors_C,
                  data = dat.nssi.behavior,
                  studlab = paste(Study),
                  comb.fixed = FALSE,
                  comb.random = TRUE,
                  method.tau = "ML",
                  hakn = TRUE,
                  prediction = TRUE,
                  sm = "MD")

m.nssi.behavior.c

con.nssi.bhx<-find.outliers(m.nssi.behavior.c)

jpeg(file='NSSI behavior.consequence.out.jpeg',
     width=10, height=6, units="in", res=300)
forest(con.nssi.bhx$m.random, layout="RevMan5", digits.sd=2)
dev.off()
```

```{r}
dat.suicidal.thoughts<-data[which(data$Study=="Bresin et al. 2013"|data$Study=="Czyz et al. 2017"|data$Study=="Forkmann et al., 2018"|data$Study=="Husky et al., 2017"|data$Study=="Kaurin et al., Under Review"|data$Study=="Kiekens et al., 2020"|data$Study=="Kleiman et al., 2017"|data$Study=="Kleiman et al., 2018"|data$Study=="Kuehn et al., In Prep"|data$Study=="Peters et al., 2020"|data$Study=="Salim et al., 2019"|data$Study=="Wolford-Clevenger et al., 2019"), ]

m.suicidal.thoughts.c <- metagen(Suicidal.thoughts_C,
                  SP_Suicidal.thoughts_C,
                  data = dat.suicidal.thoughts,
                  studlab = paste(Study),
                  comb.fixed = FALSE,
                  comb.random = TRUE,
                  method.tau = "ML",
                  hakn = TRUE,
                  prediction = TRUE,
                  sm = "MD")

m.suicidal.thoughts.c

con.sui<-find.outliers(m.suicidal.thoughts.c)

jpeg('Sui Thoughts.consequence.t+1.jpeg',
     width=10, height=6, units="in", res=300)
forest(m.suicidal.thoughts.c, layout="RevMan5", digits.sd=2)
dev.off()
```